import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { ArrowRightIcon, BookIcon, ChartIcon } from "@/components/ui/icons";

export const metadata: Metadata = { title: "Previous Year Questions", description: "Explore NEET previous-year questions organised by year and subject." };
const years = [2025, 2024, 2023, 2022, 2021, 2020];

export default function PyqPage() {
  return <>
    <section className="relative overflow-hidden bg-[#173f34] text-white"><div className="dot-field absolute inset-0 opacity-25" /><Container className="relative grid gap-10 py-16 lg:grid-cols-[1fr_0.45fr] lg:items-end lg:py-20"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-300">Previous years</p><h1 className="mt-4 max-w-3xl text-5xl font-bold leading-[1.02] tracking-[-0.05em] sm:text-6xl">Learn the patterns.<br />Respect the syllabus.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-emerald-50/70">Use verified previous-year questions to recognise recurring concepts and understand how NEET turns knowledge into choices.</p></div><div className="border-l border-white/20 pl-6"><ChartIcon className="size-7 text-emerald-300" /><p className="mt-4 text-sm leading-6 text-white/60">PYQ content is added only after source verification. Placeholder years below are clearly marked.</p></div></Container></section>
    <section className="py-14 sm:py-20"><Container><div className="grid gap-10 lg:grid-cols-[0.35fr_1fr]"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-700">Year archive</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Trace the exam over time.</h2></div><div className="border-t border-slate-300">{years.map((year, index) => <div key={year} className="group grid grid-cols-[5rem_1fr_auto] items-center gap-4 border-b border-slate-200 py-5 transition hover:bg-white sm:grid-cols-[7rem_1fr_auto] sm:px-4"><span className="text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">{year}</span><span><strong className="block text-sm text-slate-900">NEET question set</strong><span className="mt-1 block text-xs text-slate-500">{index === 0 ? "Content being verified" : "Archive placeholder"}</span></span><span className="grid size-10 place-items-center rounded-full border border-slate-200 text-slate-300 transition group-hover:border-emerald-200 group-hover:bg-emerald-50 group-hover:text-emerald-700"><ArrowRightIcon className="size-4" /></span></div>)}</div></div><div className="relative mt-14 overflow-hidden rounded-[1.75rem] bg-slate-950 p-7 text-white sm:p-9"><div className="dot-field absolute inset-0 opacity-20" /><div className="relative flex flex-col gap-6 sm:flex-row sm:items-center"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-emerald-400/15 text-emerald-300"><BookIcon /></span><div><p className="text-sm font-semibold text-emerald-300">Quality before quantity</p><h2 className="mt-1 text-xl font-bold">Only verified questions will be labelled as official PYQs.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Source year, answer and explanation will remain tied to the question record.</p></div></div></div></Container></section>
  </>;
}
